// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/smc-home/Bold.tsx": () => import("../components/mockups/smc-home/Bold.tsx"),
  "./components/mockups/smc-home/Cinematic.tsx": () => import("../components/mockups/smc-home/Cinematic.tsx"),
  "./components/mockups/smc-home/Editorial.tsx": () => import("../components/mockups/smc-home/Editorial.tsx")
};
